<?xml version='1.0' encoding='utf-8'?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Manina.Windows.Forms</RootNamespace>
    <AssemblyName>ImageListView</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <DefineConstants>$(DefineConstants);BONUSPACK</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="ColumnHeaderCollectionEditor.cs" />
    <Compile Include="ColumnHeaderCollectionTypeConverter.cs" />
    <Compile Include="BonusRenderers.cs" />
    <Compile Include="DebugRenderer.cs" />
    <Compile Include="ImageListViewResources.tr.Designer.cs">
      <DependentUpon>ImageListViewResources.tr.resx</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Include="ImageListViewRenderers.cs" />
    <Compile Include="Enums.cs" />
    <Compile Include="Events.cs" />
    <Compile Include="HitInfo.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Include="ImageListView.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Include="ImageListViewCacheManager.cs" />
    <Compile Include="ImageListViewColumnHeader.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Include="ImageListViewColumnHeaderCollection.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Include="ImageListViewDesigner.cs">
    </Compile>
    <Compile Include="ImageListViewItem.cs" />
    <Compile Include="ImageListViewItemCacheManager.cs" />
    <Compile Include="ImageListViewItemCollection.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Include="ImageListViewLayoutManager.cs">
    </Compile>
    <Compile Include="ImageListViewRenderer.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Include="ImageListViewSelectedItemCollection.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Include="ImageListViewSerializer.cs" />
    <Compile Include="ImageListViewNavigationManager.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="ImageListViewResources.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>ImageListViewResources.resx</DependentUpon>
    </Compile>
    <Compile Include="Utility.cs" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="ImageListViewResources.tr.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ImageListViewResources.tr.Designer.cs</LastGenOutput>
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="ImageListView.bmp" />
    <EmbeddedResource Include="ImageListViewResources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ImageListViewResources.Designer.cs</LastGenOutput>
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <None Include="app.config" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\image.png" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\exclamation.png" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\SortAscending.png" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\SortDescending.png" />
  </ItemGroup>
  <ItemGroup>
    </ItemGroup>
</Project>