//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSP.Bina.Ocr.DesktopApplication.V3.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DSP.Bina.Ocr.DesktopApplication.V3.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        internal static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bina OCR
        ///Bina is an image-to-text application that uses optical character recognition (OCR) to extract text from images and PDF files and save it as a text file. It offers an alternative to manually typing printed content, converting documents into digital text quickly and accurately.
        ///.
        /// </summary>
        internal static string AboutUsDescription {
            get {
                return ResourceManager.GetString("AboutUsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust Image Brightness.
        /// </summary>
        internal static string AdjustImageBrightness {
            get {
                return ResourceManager.GetString("AdjustImageBrightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust Image Contrast.
        /// </summary>
        internal static string AdjustImageContrast {
            get {
                return ResourceManager.GetString("AdjustImageContrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust Image Gamma.
        /// </summary>
        internal static string AdjustImageGamma {
            get {
                return ResourceManager.GetString("AdjustImageGamma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust Image Threshold.
        /// </summary>
        internal static string AdjustImageThreshold {
            get {
                return ResourceManager.GetString("AdjustImageThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bina OCR.
        /// </summary>
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch processing completed..
        /// </summary>
        internal static string BatchProcessingCompleted {
            get {
                return ResourceManager.GetString("BatchProcessingCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch        ///
        ///Processing.
        /// </summary>
        internal static string BatchProcessingTwoLines {
            get {
                return ResourceManager.GetString("BatchProcessingTwoLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bina Version {0}.
        /// </summary>
        internal static string BinaVersionFormat {
            get {
                return ResourceManager.GetString("BinaVersionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bina Version 1.
        /// </summary>
        internal static string BinaVersionOne {
            get {
                return ResourceManager.GetString("BinaVersionOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrast.
        /// </summary>
        internal static string Contrast {
            get {
                return ResourceManager.GetString("Contrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert Image to Grayscale.
        /// </summary>
        internal static string ConvertImageToGrayscale {
            get {
                return ResourceManager.GetString("ConvertImageToGrayscale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert Image to Monochrome.
        /// </summary>
        internal static string ConvertImageToMonochrome {
            get {
                return ResourceManager.GetString("ConvertImageToMonochrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to Text.
        /// </summary>
        internal static string ConvertToText {
            get {
                return ResourceManager.GetString("ConvertToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    Convert to Text   .
        /// </summary>
        internal static string ConvertToTextTab {
            get {
                return ResourceManager.GetString("ConvertToTextTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary.
        /// </summary>
        internal static string Dictionary {
            get {
                return ResourceManager.GetString("Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document layout:.
        /// </summary>
        internal static string DocumentLayoutLabel {
            get {
                return ResourceManager.GetString("DocumentLayoutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep Learning.
        /// </summary>
        internal static string EngineDeep {
            get {
                return ResourceManager.GetString("EngineDeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structural.
        /// </summary>
        internal static string EngineStructural {
            get {
                return ResourceManager.GetString("EngineStructural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structural and Deep Learning.
        /// </summary>
        internal static string EngineStructuralAndDeep {
            get {
                return ResourceManager.GetString("EngineStructuralAndDeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is being used by another application..
        /// </summary>
        internal static string FileInUse {
            get {
                return ResourceManager.GetString("FileInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        internal static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamma.
        /// </summary>
        internal static string Gamma {
            get {
                return ResourceManager.GetString("Gamma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    Help   .
        /// </summary>
        internal static string HelpTab {
            get {
                return ResourceManager.GetString("HelpTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Brightness.
        /// </summary>
        internal static string ImageBrightness {
            get {
                return ResourceManager.GetString("ImageBrightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Processing.
        /// </summary>
        internal static string ImageProcessing {
            get {
                return ResourceManager.GetString("ImageProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    Image Processing   .
        /// </summary>
        internal static string ImageProcessingTab {
            get {
                return ResourceManager.GetString("ImageProcessingTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Size.
        /// </summary>
        internal static string ImageSize {
            get {
                return ResourceManager.GetString("ImageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected file path is invalid..
        /// </summary>
        internal static string InvalidFilePath {
            get {
                return ResourceManager.GetString("InvalidFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected folder path is invalid..
        /// </summary>
        internal static string InvalidFolderPath {
            get {
                return ResourceManager.GetString("InvalidFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected font size is invalid..
        /// </summary>
        internal static string InvalidFontSize {
            get {
                return ResourceManager.GetString("InvalidFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input data format is invalid..
        /// </summary>
        internal static string InvalidInputFormat {
            get {
                return ResourceManager.GetString("InvalidInputFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert Image Colors.
        /// </summary>
        internal static string InvertImageColors {
            get {
                return ResourceManager.GetString("InvertImageColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language and Layout.
        /// </summary>
        internal static string LanguageAndLayout {
            get {
                return ResourceManager.GetString("LanguageAndLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string LanguageEnglish {
            get {
                return ResourceManager.GetString("LanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persian and English.
        /// </summary>
        internal static string LanguageMixed {
            get {
                return ResourceManager.GetString("LanguageMixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persian.
        /// </summary>
        internal static string LanguagePersian {
            get {
                return ResourceManager.GetString("LanguagePersian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic layout with orientation and script detection.
        /// </summary>
        internal static string LayoutAutomaticWithOrientationAndScriptDetection {
            get {
                return ResourceManager.GetString("LayoutAutomaticWithOrientationAndScriptDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic layout without orientation and script detection.
        /// </summary>
        internal static string LayoutAutomaticWithoutOrientationAndScriptDetection {
            get {
                return ResourceManager.GetString("LayoutAutomaticWithoutOrientationAndScriptDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single word in a circle.
        /// </summary>
        internal static string LayoutCircularWord {
            get {
                return ResourceManager.GetString("LayoutCircularWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assume multiple layout modes.
        /// </summary>
        internal static string LayoutMultipleModes {
            get {
                return ResourceManager.GetString("LayoutMultipleModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orientation and script detection.
        /// </summary>
        internal static string LayoutOrientationAndScriptDetection {
            get {
                return ResourceManager.GetString("LayoutOrientationAndScriptDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw line of text.
        /// </summary>
        internal static string LayoutRawLine {
            get {
                return ResourceManager.GetString("LayoutRawLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single character.
        /// </summary>
        internal static string LayoutSingleCharacter {
            get {
                return ResourceManager.GetString("LayoutSingleCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single column of text.
        /// </summary>
        internal static string LayoutSingleColumn {
            get {
                return ResourceManager.GetString("LayoutSingleColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single line of text.
        /// </summary>
        internal static string LayoutSingleLine {
            get {
                return ResourceManager.GetString("LayoutSingleLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single block of text.
        /// </summary>
        internal static string LayoutSingleTextBlock {
            get {
                return ResourceManager.GetString("LayoutSingleTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single block of vertically aligned text.
        /// </summary>
        internal static string LayoutSingleVerticalTextBlock {
            get {
                return ResourceManager.GetString("LayoutSingleVerticalTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sparse text.
        /// </summary>
        internal static string LayoutSparseText {
            get {
                return ResourceManager.GetString("LayoutSparseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sparse text with orientation and script detection.
        /// </summary>
        internal static string LayoutSparseTextWithOrientationAndScriptDetection {
            get {
                return ResourceManager.GetString("LayoutSparseTextWithOrientationAndScriptDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without orientation or script detection.
        /// </summary>
        internal static string LayoutWithoutOrientationAndScriptDetection {
            get {
                return ResourceManager.GetString("LayoutWithoutOrientationAndScriptDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string LoadSelectedPages {
            get {
                return ResourceManager.GetString("LoadSelectedPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter page numbers in the format 1, 4-5, 7-10. (Use &quot;-&quot; for page ranges and &quot;,&quot; to separate ranges.).
        /// </summary>
        internal static string PageSelectionInstructions {
            get {
                return ResourceManager.GetString("PageSelectionInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-processing.
        /// </summary>
        internal static string PostProcessing {
            get {
                return ResourceManager.GetString("PostProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing ....
        /// </summary>
        internal static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing completed..
        /// </summary>
        internal static string ProcessingCompleted {
            get {
                return ResourceManager.GetString("ProcessingCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing engine:.
        /// </summary>
        internal static string ProcessingEngineLabel {
            get {
                return ResourceManager.GetString("ProcessingEngineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing {0} ....
        /// </summary>
        internal static string ProcessingImageFormat {
            get {
                return ResourceManager.GetString("ProcessingImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process        ///
        ///.
        /// </summary>
        internal static string ProcessWithLineBreak {
            get {
                return ResourceManager.GetString("ProcessWithLineBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognition language:.
        /// </summary>
        internal static string RecognitionLanguageLabel {
            get {
                return ResourceManager.GetString("RecognitionLanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save        ///
        ///All.
        /// </summary>
        internal static string SaveAllTwoLines {
            get {
                return ResourceManager.GetString("SaveAllTwoLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved successfully..
        /// </summary>
        internal static string SaveCompleted {
            get {
                return ResourceManager.GetString("SaveCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save        ///
        ///File.
        /// </summary>
        internal static string SaveTwoLines {
            get {
                return ResourceManager.GetString("SaveTwoLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving ....
        /// </summary>
        internal static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all pages.
        /// </summary>
        internal static string SelectAllPages {
            get {
                return ResourceManager.GetString("SelectAllPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select pages from {0} .
        /// </summary>
        internal static string SelectFilePagesFormat {
            get {
                return ResourceManager.GetString("SelectFilePagesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an image first..
        /// </summary>
        internal static string SelectImageFirst {
            get {
                return ResourceManager.GetString("SelectImageFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharpen Image.
        /// </summary>
        internal static string SharpenImage {
            get {
                return ResourceManager.GetString("SharpenImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smooth Image.
        /// </summary>
        internal static string SmoothImage {
            get {
                return ResourceManager.GetString("SmoothImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold.
        /// </summary>
        internal static string Threshold {
            get {
                return ResourceManager.GetString("Threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string UiLanguageEnglish {
            get {
                return ResourceManager.GetString("UiLanguageEnglish", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UI language:.
        /// </summary>
        internal static string UiLanguageLabel {
            get {
                return ResourceManager.GetString("UiLanguageLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to فارسی.
        /// </summary>
        internal static string UiLanguagePersian {
            get {
                return ResourceManager.GetString("UiLanguagePersian", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred. Please contact support..
        /// </summary>
        internal static string UnexpectedErrorContactSupport {
            get {
                return ResourceManager.GetString("UnexpectedErrorContactSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use dictionary.
        /// </summary>
        internal static string UseDictionary {
            get {
                return ResourceManager.GetString("UseDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        internal static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
    }
}
