<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>DSP.Khana.Ocr.PostPRocessing</RootNamespace>
    <AssemblyName>DSP.Khana.Ocr.PostPRocessing</AssemblyName>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="KhanaPostProcessing.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>
</Project>
