<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Bina.Ocr.Wapper</RootNamespace>
    <AssemblyName>Bina.Ocr.Wapper</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="BinaOcr.cs" />
    <Compile Include="Enum.cs" />
    <Compile Include="LogManager.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DSP.Khana.Ocr.Engine.v5\DSP.Khana.Ocr.Engine.v5.csproj">
      <Project>{eead4ce5-339d-4eea-befe-6d021d76be13}</Project>
      <Name>DSP.Khana.Ocr.Engine.v5</Name>
    </ProjectReference>
    <ProjectReference Include="..\DSP.Khana.Ocr.PostPRocessing\DSP.Khana.Ocr.PostProcessing.csproj">
      <Project>{0b166208-4627-4726-8b43-90bbffb356ae}</Project>
      <Name>DSP.Khana.Ocr.PostProcessing</Name>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Properties\BinaOcrEngineV5_64.dll" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Properties\BinaOcrEngineV5_86.dll" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Properties\liblept1780_64.dll" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Properties\liblept1780_86.dll" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Properties\Data.zip" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Properties\DSP.Tools32.dll" />
    <EmbeddedResource Include="Properties\DSP.Tools64.dll" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="10.0.12" />
  </ItemGroup>
</Project>
