<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>DSP.Khana.ImageTools</RootNamespace>
    <AssemblyName>DSP.Khana.ImageTools</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Models\GmseDeskew.cs" />
    <Compile Include="Models\GrayBMP_File.cs" />
    <Compile Include="Models\ImageConverter.cs" />
    <Compile Include="Models\ImageHelper.cs" />
    <Compile Include="Models\PDFConvert.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="DSP.Tools32.dll" />
    <Content Include="DSP.Tools64.dll" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="10.0.12" />
  </ItemGroup>
</Project>
